--
- name: Twarde zabezpieczenie serwera
  hosts: ubuntuvm
  become: yes

  vars:
    new_user: devops
    ssh_public_key: "your_ssh_public_key"
  tasks:
    - name: Tworzenie nowego użytkownika
      user:
        name: "{{ new_user }}"
        groups: sudo
        shell: /bin/bash
        create_home: yes

    - name: Tworzenie katalogu .ssh
      file:
        path: "/home/{{ new_user }}/.ssh"
        state: directory
        mode: '0700'
        owner: "{{ new_user }}"
        group: "{{ new_user }}"

    - name: Dodanie klucza SSH
      copy:
        content: "{{ ssh_public_key }}"
        dest: "/home/{{ new_user }}/.ssh/authorized_keys"
        mode: '0600'
        owner: "{{ new_user }}"
        group: "{{ new_user }}"

    - name: Instalacja UFW
      apt:
        name: ufw
        state: present
        update_cache: yes

    - name: Zezwolenie na SSH
      ufw:
        rule: allow
        port: '22'
        proto: tcp

    - name: Włączenie UFW
      ufw:
        state: enabled

    - name: Zablokowanie logowania root i hasłowego
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?PermitRootLogin'
        line: 'PermitRootLogin no'
        state: present

    - name: Wyłączenie logowania hasłem
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?PasswordAuthentication'
        line: 'PasswordAuthentication no'
        state: present

    - name: Restart SSH
      service:
        name: ssh
        state: restarted
